before_install: # Fix: https://github.com/jitpack/jitpack.io/issues/4506#issuecomment-864562270
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk update
  - sdk install java 17.0.7-graal
  - sdk use java 17.0.7-graal
